### ISSUE TITLE
Did you really need an ArrayList?

### ISSUE THREAD

**Issue by yawboakye** [lawkaringithi/FigureInWords#6]
I've been trying to wrap my head around why you needed an `ArrayList`. In the following [lines](https://github.com/lawkaringithi/FigureInWords/blob/8fb6522f7267ed1d5da9895b40f1b98981aad433/src/figures/FigureInWords.java#L23-L25) you populate it with elements from an array whose size was already know, or could be determined. That feels like a misuse of resource to me.

**Comment by lawkaringithi** [comment]
The ArrayList has an indexOf method that was useful to get the index of a certain item in the list. I will transfer all values to the ArrayList and do away with the Arrays
